source('project1data.R')
data <- dataf()
png(filename='plot3.png', width=480,height=480,units='px')
x <- strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
plot(x, data$Sub_metering_1, type = 'l', col='black',ylab = "Energy sub metering", xlab = "")
lines(x, data$Sub_metering_2, col = "red")
lines(x, data$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
